### ISSUE TITLE
Replace gzip with pigz

### ISSUE THREAD

**Issue by amorphic** [BytemarkHosting/pairvm#4]
Pairvm currently uses `gzip` to archive memory dumps for backup purposes.

For some time we have been using [pigz](http://zlib.net/pigz/) instead. Being a drop-in replacement for `gzip` it allows us to take advantage of multiple cores, speeding up our backup times without changing anything. E.g.

```
<           return ["-incoming", "exec: gzip -c -d #{@machine.memory_dump_file}"]

---
>           return ["-incoming", "exec: pigz -c -d #{@machine.memory_dump_file}"]
```

Would you be interested in a PR for this? We haven't gone so far as to optionally use `gzip` or `pigz` depending on availability. But as `pigz` is now a standard inclusion in package repos it arguably wouldn't be a big deal to make it a dependency.

**Comment by jamesfcarter** [comment]
If it were to be a hard dependency, then pairvm should probably check for that in the first_time_setup checks, but beyond that I have no objections.
